const data = [
    {
        title: "Dr.Paula",
        consultorio: "Consultório de Santo Tirso",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "David",
        consultorio: "Consultório de Bragança",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Ricardo",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "David",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Samu",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Afonso",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Samu",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Samu",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Ricardo",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
    {
        title: "Consultório Mata Real",
        consultorio: "Consultório Mata Real",
        distancia: 2.5,
        preco: 100,
        phone: 912345678,
        imgUrl: require('./assets/DrPaula.png'),
    },
]


export default data;